# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b76c42878d21ec312c9b8c61cecf92b2e7b19d0b6d0132eb1385170500c37a217ecbb7a40bb5b3dd3dc93e559adb8156428c7f532a1769a30758affda787e57b

test:
  secret_key_base: 0b8f989acadac65f6bd437af69af4a930f7aa918a23dcb27ad48546c673dcc9543f8dce8b16654a9f15fd444175b747fe8954307a78754304b5db04b8f4d7126

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
